all:

clean:
	rm a.out b.out

all-test:
	make -C ~/Fall\ 2014/cs345/PA1 
	../lexer tests.txt > a.out
	/projects/cs345.tdillig/lexer tests.txt > b.out

simple:
	make -C ~/Fall\ 2014/cs345/PA1 
	../lexer simple.L
	/projects/cs345.tdillig/lexer simple.L

