(*33 1 "duck" identifier*)

(*let y = lambda x,y.(x(y y)) in (y 5)*)

(*print ("STRING")*)
(*((2) + 3) * 4
 2 + 3 * 4 
*)

(*(2 * 3) + 4 * ((3) + (5 - 97)) *)

(*((3 + 5 - 1) / 2 = 2 - 1 * 200) = 23 *)

(*(print (if (3*5 >= 16 - 1) then (if 2 + 2 >= ((1 * 100)) then "nested if-then" else "nested else")  else "weird"))*)

(*let x = print "hello" in x*)

(*let x = (if 2 * 4 <> 8 then print "this shouldn't run" else print "Winner winner" + "chicken" + "dinner") in x*)

(*let y = lambda x.lambda z.(let t = ReadString in let _ = (print t) in 0) in (y 5)*)

(*isNil x *)
(1+2)@3
